### PR TITLE
build: update dependencies

### PR DESCRIPTION
**Pull request by firstred**
[//]: # (Excluding translations make sure this pull request is linked to an issue first! 
        This helps us keep track of all the changes when we release a new version)

I was having a hard time building bunqDesktop due to outdated dependencies. If it's okay to limit the configurations on which bunqDesktop can be built, then it should now be easier to ensure building works on compatible environments.

This PR:
- Updates a few core dependencies to make it work on node.js 12+
- Sets environment restrictions in `package.json`

### CODE REVIEW

**Comment by firstred** [comment]
Thanks for merging this PR! It's probably a good idea to update more dependencies. Which ones would you like to see updated first?
Also, do you mind if I refactor in the Redux Starter Kit? I am trying to fix a few background processing issues and I expect that reducing the amount of boilerplate is going to be a tremendous help.

**Comment by Crecket** [comment]
I'm always open to code to improve the project. I still need to find time to fix the deprecated API endpoints first which I hope I can do next weekend.

**Comment by firstred** [comment]
Great!

Refactoring Redux probably does involve renaming several actions, but when successful, it should be a lot easier to manage the store with the starter kit. I'll try to figure out what else we need to do (or document?) to make participating easier; hopefully, we can attract more contributors that way to keep the project going.

Thanks for creating bunqDesktop! It has saved me a lot of time.

**Comment by Crecket** [comment]
Yeah I just gotta rewrite the bunqjsclient with the new endpoints which is a breaking change in there, and then rewrite all the actions and reducers in bundesktop afterwards

**Pull request merged**
