### PR TITLE
build: run nvm install with .nvmrc

### PR DESCRIPTION
**Pull request by firstred**
Travis seems to be skipping the installation of node.js 12. It is effectively still using version 11, due to the `before_install` "override".
https://travis-ci.com/firstred/bunqDesktop/jobs/278126591#L257

Adding a `.nvmrc` file and running `nvm install` in the `before_install` step solves the issue.

### CODE REVIEW

**Comment by Crecket** [comment]
Thanks, I tested setting the higher node version directly but travis isn't detecting it for some reason

**Comment by firstred** [comment]
Looks like the error message is coming from a docker container.

**Comment by Crecket** [comment]
Ah yeah it's probably the electronuserland/builder:wine image, see electron-userland/electron-builder#4377

Do we need node 12? Honestly tempted to roll it back for this release if we have to use all these workarounds just to get it to work

**Comment by firstred** [comment]
I'm wondering if we can provide a custom Dockerfile to install nvm and the right node.js version.

I have tried to restrict the node.js version to the current LTS to prevent "works on my machine" kind of situations. Having the same build environment everywhere would be great.

**Comment by firstred** [comment]
Yes, that worked! PR: https://github.com/bunqCommunity/bunqDesktop/pull/555

**Pull request merged**
